=begin
#Togai Apis

#APIs for Togai App

The version of the OpenAPI document: 1.0
Contact: engg@togai.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module TogaiClient
  # Billing Entitlement rate card
  class BillingEntitlementRateCard
    attr_accessor :feature_id

    attr_accessor :feature_configs

    # A tag string to group rate cards
    attr_accessor :tag

    attr_accessor :invoice_timing

    # Name your rate card, this will be used in invoice
    attr_accessor :display_name

    # Unique identifier for the rate card in a price plan. If left null it is auto-generated.
    attr_accessor :name

    attr_accessor :rate_plan

    attr_accessor :rate_values

    attr_accessor :recurrence_config

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'feature_id' => :'featureId',
        :'feature_configs' => :'featureConfigs',
        :'tag' => :'tag',
        :'invoice_timing' => :'invoiceTiming',
        :'display_name' => :'displayName',
        :'name' => :'name',
        :'rate_plan' => :'ratePlan',
        :'rate_values' => :'rateValues',
        :'recurrence_config' => :'recurrenceConfig'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'feature_id' => :'String',
        :'feature_configs' => :'Array<FeatureConfig>',
        :'tag' => :'String',
        :'invoice_timing' => :'InvoiceTiming',
        :'display_name' => :'String',
        :'name' => :'String',
        :'rate_plan' => :'RatePlan',
        :'rate_values' => :'Array<RateValue>',
        :'recurrence_config' => :'RecurrenceConfig'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TogaiClient::BillingEntitlementRateCard` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TogaiClient::BillingEntitlementRateCard`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'feature_id')
        self.feature_id = attributes[:'feature_id']
      else
        self.feature_id = nil
      end

      if attributes.key?(:'feature_configs')
        if (value = attributes[:'feature_configs']).is_a?(Array)
          self.feature_configs = value
        end
      else
        self.feature_configs = nil
      end

      if attributes.key?(:'tag')
        self.tag = attributes[:'tag']
      end

      if attributes.key?(:'invoice_timing')
        self.invoice_timing = attributes[:'invoice_timing']
      else
        self.invoice_timing = nil
      end

      if attributes.key?(:'display_name')
        self.display_name = attributes[:'display_name']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'rate_plan')
        self.rate_plan = attributes[:'rate_plan']
      else
        self.rate_plan = nil
      end

      if attributes.key?(:'rate_values')
        if (value = attributes[:'rate_values']).is_a?(Array)
          self.rate_values = value
        end
      else
        self.rate_values = nil
      end

      if attributes.key?(:'recurrence_config')
        self.recurrence_config = attributes[:'recurrence_config']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @feature_id.nil?
        invalid_properties.push('invalid value for "feature_id", feature_id cannot be nil.')
      end

      if @feature_configs.nil?
        invalid_properties.push('invalid value for "feature_configs", feature_configs cannot be nil.')
      end

      if @feature_configs.length < 1
        invalid_properties.push('invalid value for "feature_configs", number of items must be greater than or equal to 1.')
      end

      if @invoice_timing.nil?
        invalid_properties.push('invalid value for "invoice_timing", invoice_timing cannot be nil.')
      end

      if @rate_plan.nil?
        invalid_properties.push('invalid value for "rate_plan", rate_plan cannot be nil.')
      end

      if @rate_values.nil?
        invalid_properties.push('invalid value for "rate_values", rate_values cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @feature_id.nil?
      return false if @feature_configs.nil?
      return false if @feature_configs.length < 1
      return false if @invoice_timing.nil?
      return false if @rate_plan.nil?
      return false if @rate_values.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] feature_configs Value to be assigned
    def feature_configs=(feature_configs)
      if feature_configs.nil?
        fail ArgumentError, 'feature_configs cannot be nil'
      end

      if feature_configs.length < 1
        fail ArgumentError, 'invalid value for "feature_configs", number of items must be greater than or equal to 1.'
      end

      @feature_configs = feature_configs
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          feature_id == o.feature_id &&
          feature_configs == o.feature_configs &&
          tag == o.tag &&
          invoice_timing == o.invoice_timing &&
          display_name == o.display_name &&
          name == o.name &&
          rate_plan == o.rate_plan &&
          rate_values == o.rate_values &&
          recurrence_config == o.recurrence_config
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [feature_id, feature_configs, tag, invoice_timing, display_name, name, rate_plan, rate_values, recurrence_config].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = TogaiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
