=begin
#Togai Apis

#APIs for Togai App

The version of the OpenAPI document: 1.0
Contact: engg@togai.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module TogaiClient
  class CreditDetailsResponse
    attr_accessor :account_id

    attr_accessor :purpose

    # List of entity ids for which the credit is applicable. If null or empty, the credit is applicable to all ids. This list can accept special values like: - ALL_USAGE_METER_RATE_CARDS: To apply the credit to all usage meter rate cards - ALL_FIXED_FEE_RATE_CARDS: To apply the credit to all fixed fee rate cards 
    attr_accessor :applicable_entity_ids

    attr_accessor :effective_from

    attr_accessor :effective_until

    attr_accessor :credit_amount

    attr_accessor :priority

    # The entity through which the credit has been granted
    attr_accessor :grantor_id

    # The idempotency key for uniqueness of the credit record
    attr_accessor :idempotency_key

    # Identifier of credits
    attr_accessor :id

    attr_accessor :customer_id

    attr_accessor :status

    attr_accessor :credit_unit

    attr_accessor :hold_amount

    attr_accessor :consumed_amount

    attr_accessor :created_at

    attr_accessor :updated_at

    attr_accessor :transactions

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'account_id' => :'accountId',
        :'purpose' => :'purpose',
        :'applicable_entity_ids' => :'applicableEntityIds',
        :'effective_from' => :'effectiveFrom',
        :'effective_until' => :'effectiveUntil',
        :'credit_amount' => :'creditAmount',
        :'priority' => :'priority',
        :'grantor_id' => :'grantorId',
        :'idempotency_key' => :'idempotencyKey',
        :'id' => :'id',
        :'customer_id' => :'customerId',
        :'status' => :'status',
        :'credit_unit' => :'creditUnit',
        :'hold_amount' => :'holdAmount',
        :'consumed_amount' => :'consumedAmount',
        :'created_at' => :'createdAt',
        :'updated_at' => :'updatedAt',
        :'transactions' => :'transactions'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'account_id' => :'String',
        :'purpose' => :'String',
        :'applicable_entity_ids' => :'Array<String>',
        :'effective_from' => :'Date',
        :'effective_until' => :'Date',
        :'credit_amount' => :'Float',
        :'priority' => :'Integer',
        :'grantor_id' => :'String',
        :'idempotency_key' => :'String',
        :'id' => :'String',
        :'customer_id' => :'String',
        :'status' => :'String',
        :'credit_unit' => :'String',
        :'hold_amount' => :'Float',
        :'consumed_amount' => :'Float',
        :'created_at' => :'Time',
        :'updated_at' => :'Time',
        :'transactions' => :'Array<CreditTransaction>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'Credit'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TogaiClient::CreditDetailsResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TogaiClient::CreditDetailsResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'account_id')
        self.account_id = attributes[:'account_id']
      else
        self.account_id = nil
      end

      if attributes.key?(:'purpose')
        self.purpose = attributes[:'purpose']
      else
        self.purpose = nil
      end

      if attributes.key?(:'applicable_entity_ids')
        if (value = attributes[:'applicable_entity_ids']).is_a?(Array)
          self.applicable_entity_ids = value
        end
      end

      if attributes.key?(:'effective_from')
        self.effective_from = attributes[:'effective_from']
      else
        self.effective_from = nil
      end

      if attributes.key?(:'effective_until')
        self.effective_until = attributes[:'effective_until']
      end

      if attributes.key?(:'credit_amount')
        self.credit_amount = attributes[:'credit_amount']
      end

      if attributes.key?(:'priority')
        self.priority = attributes[:'priority']
      else
        self.priority = nil
      end

      if attributes.key?(:'grantor_id')
        self.grantor_id = attributes[:'grantor_id']
      end

      if attributes.key?(:'idempotency_key')
        self.idempotency_key = attributes[:'idempotency_key']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'customer_id')
        self.customer_id = attributes[:'customer_id']
      else
        self.customer_id = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'credit_unit')
        self.credit_unit = attributes[:'credit_unit']
      end

      if attributes.key?(:'hold_amount')
        self.hold_amount = attributes[:'hold_amount']
      end

      if attributes.key?(:'consumed_amount')
        self.consumed_amount = attributes[:'consumed_amount']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'transactions')
        if (value = attributes[:'transactions']).is_a?(Array)
          self.transactions = value
        end
      else
        self.transactions = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @account_id.nil?
        invalid_properties.push('invalid value for "account_id", account_id cannot be nil.')
      end

      if @purpose.nil?
        invalid_properties.push('invalid value for "purpose", purpose cannot be nil.')
      end

      if @effective_from.nil?
        invalid_properties.push('invalid value for "effective_from", effective_from cannot be nil.')
      end

      if @priority.nil?
        invalid_properties.push('invalid value for "priority", priority cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @id.to_s.length > 50
        invalid_properties.push('invalid value for "id", the character length must be smaller than or equal to 50.')
      end

      if @customer_id.nil?
        invalid_properties.push('invalid value for "customer_id", customer_id cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @transactions.nil?
        invalid_properties.push('invalid value for "transactions", transactions cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @account_id.nil?
      return false if @purpose.nil?
      return false if @effective_from.nil?
      return false if @priority.nil?
      return false if @id.nil?
      return false if @id.to_s.length > 50
      return false if @customer_id.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["ACTIVE", "CONSUMED", "EXPIRED", "VOIDED"])
      return false unless status_validator.valid?(@status)
      return false if @created_at.nil?
      return false if @transactions.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] applicable_entity_ids Value to be assigned
    def applicable_entity_ids=(applicable_entity_ids)
      if applicable_entity_ids.nil?
        fail ArgumentError, 'applicable_entity_ids cannot be nil'
      end

      @applicable_entity_ids = applicable_entity_ids
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      if id.to_s.length > 50
        fail ArgumentError, 'invalid value for "id", the character length must be smaller than or equal to 50.'
      end

      @id = id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["ACTIVE", "CONSUMED", "EXPIRED", "VOIDED"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          account_id == o.account_id &&
          purpose == o.purpose &&
          applicable_entity_ids == o.applicable_entity_ids &&
          effective_from == o.effective_from &&
          effective_until == o.effective_until &&
          credit_amount == o.credit_amount &&
          priority == o.priority &&
          grantor_id == o.grantor_id &&
          idempotency_key == o.idempotency_key &&
          id == o.id &&
          customer_id == o.customer_id &&
          status == o.status &&
          credit_unit == o.credit_unit &&
          hold_amount == o.hold_amount &&
          consumed_amount == o.consumed_amount &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          transactions == o.transactions
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [account_id, purpose, applicable_entity_ids, effective_from, effective_until, credit_amount, priority, grantor_id, idempotency_key, id, customer_id, status, credit_unit, hold_amount, consumed_amount, created_at, updated_at, transactions].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = TogaiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
