=begin
#Togai Apis

#APIs for Togai App

The version of the OpenAPI document: 1.0
Contact: engg@togai.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module TogaiClient
  # Contents of the event
  class Event
    # Name of the Event Schema.  Know more about [event schema](https://docs.togai.com/docs/event-schemas) 
    attr_accessor :schema_name

    # Togai restricts users to ingest events with same id within a period of *45 days*. This restriction is common for [/entitled API](/api-reference/entitlements/ingest-event-if-a-user-is-entitled-to-a-feature), [/ingest API](/api-reference/event-ingestion/ingest-events-to-togai) and [/ingestBatch API](/api-reference/event-ingestion/ingest-events-to-togai-in-batch). i.e, an id used on /ingest API will not be allowed on /ingestBatch or /entitled APIs
    attr_accessor :id

    # Source time stamp of the event. This timestamp must be in ISO 8601 format.
    attr_accessor :timestamp

    # The event will be associated with the provided account
    attr_accessor :account_id

    # Attributes are numeric values. It can be usage metric which you push to Togai
    attr_accessor :attributes

    # Dimensions are tags/labels associated with the events.
    attr_accessor :dimensions

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'schema_name' => :'schemaName',
        :'id' => :'id',
        :'timestamp' => :'timestamp',
        :'account_id' => :'accountId',
        :'attributes' => :'attributes',
        :'dimensions' => :'dimensions'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'schema_name' => :'String',
        :'id' => :'String',
        :'timestamp' => :'Time',
        :'account_id' => :'String',
        :'attributes' => :'Array<Attribute>',
        :'dimensions' => :'Hash<String, String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TogaiClient::Event` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TogaiClient::Event`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'schema_name')
        self.schema_name = attributes[:'schema_name']
      else
        self.schema_name = nil
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'timestamp')
        self.timestamp = attributes[:'timestamp']
      else
        self.timestamp = nil
      end

      if attributes.key?(:'account_id')
        self.account_id = attributes[:'account_id']
      else
        self.account_id = nil
      end

      if attributes.key?(:'attributes')
        if (value = attributes[:'attributes']).is_a?(Array)
          self.attributes = value
        end
      else
        self.attributes = nil
      end

      if attributes.key?(:'dimensions')
        if (value = attributes[:'dimensions']).is_a?(Hash)
          self.dimensions = value
        end
      else
        self.dimensions = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @schema_name.nil?
        invalid_properties.push('invalid value for "schema_name", schema_name cannot be nil.')
      end

      if @schema_name.to_s.length > 50
        invalid_properties.push('invalid value for "schema_name", the character length must be smaller than or equal to 50.')
      end

      if @schema_name.to_s.length < 1
        invalid_properties.push('invalid value for "schema_name", the character length must be great than or equal to 1.')
      end

      if !@id.nil? && @id.to_s.length > 512
        invalid_properties.push('invalid value for "id", the character length must be smaller than or equal to 512.')
      end

      if @timestamp.nil?
        invalid_properties.push('invalid value for "timestamp", timestamp cannot be nil.')
      end

      if @account_id.nil?
        invalid_properties.push('invalid value for "account_id", account_id cannot be nil.')
      end

      if @account_id.to_s.length > 512
        invalid_properties.push('invalid value for "account_id", the character length must be smaller than or equal to 512.')
      end

      if @attributes.nil?
        invalid_properties.push('invalid value for "attributes", attributes cannot be nil.')
      end

      if @attributes.length > 10
        invalid_properties.push('invalid value for "attributes", number of items must be less than or equal to 10.')
      end

      if @attributes.length < 0
        invalid_properties.push('invalid value for "attributes", number of items must be greater than or equal to 0.')
      end

      if @dimensions.nil?
        invalid_properties.push('invalid value for "dimensions", dimensions cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @schema_name.nil?
      return false if @schema_name.to_s.length > 50
      return false if @schema_name.to_s.length < 1
      return false if !@id.nil? && @id.to_s.length > 512
      return false if @timestamp.nil?
      return false if @account_id.nil?
      return false if @account_id.to_s.length > 512
      return false if @attributes.nil?
      return false if @attributes.length > 10
      return false if @attributes.length < 0
      return false if @dimensions.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] schema_name Value to be assigned
    def schema_name=(schema_name)
      if schema_name.nil?
        fail ArgumentError, 'schema_name cannot be nil'
      end

      if schema_name.to_s.length > 50
        fail ArgumentError, 'invalid value for "schema_name", the character length must be smaller than or equal to 50.'
      end

      if schema_name.to_s.length < 1
        fail ArgumentError, 'invalid value for "schema_name", the character length must be great than or equal to 1.'
      end

      @schema_name = schema_name
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      if id.to_s.length > 512
        fail ArgumentError, 'invalid value for "id", the character length must be smaller than or equal to 512.'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] account_id Value to be assigned
    def account_id=(account_id)
      if account_id.nil?
        fail ArgumentError, 'account_id cannot be nil'
      end

      if account_id.to_s.length > 512
        fail ArgumentError, 'invalid value for "account_id", the character length must be smaller than or equal to 512.'
      end

      @account_id = account_id
    end

    # Custom attribute writer method with validation
    # @param [Object] attributes Value to be assigned
    def attributes=(attributes)
      if attributes.nil?
        fail ArgumentError, 'attributes cannot be nil'
      end

      if attributes.length > 10
        fail ArgumentError, 'invalid value for "attributes", number of items must be less than or equal to 10.'
      end

      if attributes.length < 0
        fail ArgumentError, 'invalid value for "attributes", number of items must be greater than or equal to 0.'
      end

      @attributes = attributes
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          schema_name == o.schema_name &&
          id == o.id &&
          timestamp == o.timestamp &&
          account_id == o.account_id &&
          attributes == o.attributes &&
          dimensions == o.dimensions
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [schema_name, id, timestamp, account_id, attributes, dimensions].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = TogaiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
