=begin
#Togai Apis

#APIs for Togai App

The version of the OpenAPI document: 1.0
Contact: engg@togai.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module TogaiClient
  class ExpiryType
    PRICING_CYCLE = "PRICING_CYCLE".freeze
    NO_EXPIRY = "NO_EXPIRY".freeze
    CUSTOM = "CUSTOM".freeze

    def self.all_vars
      @all_vars ||= [PRICING_CYCLE, NO_EXPIRY, CUSTOM].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ExpiryType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ExpiryType"
    end
  end
end
