=begin
#Togai Apis

#APIs for Togai App

The version of the OpenAPI document: 1.0
Contact: engg@togai.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module TogaiClient
  class InvoicesStatus
    DRAFT = "DRAFT".freeze
    DUE = "DUE".freeze
    PAID = "PAID".freeze
    VOID = "VOID".freeze
    UN_COLLECTIBLE = "UN_COLLECTIBLE".freeze
    REFUND_INITIATED = "REFUND_INITIATED".freeze
    REFUND_COMPLETED = "REFUND_COMPLETED".freeze
    MERGED = "MERGED".freeze
    PARTIALLY_PAID = "PARTIALLY_PAID".freeze

    def self.all_vars
      @all_vars ||= [DRAFT, DUE, PAID, VOID, UN_COLLECTIBLE, REFUND_INITIATED, REFUND_COMPLETED, MERGED, PARTIALLY_PAID].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if InvoicesStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #InvoicesStatus"
    end
  end
end
