=begin
#Togai Apis

#APIs for Togai App

The version of the OpenAPI document: 1.0
Contact: engg@togai.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module TogaiClient
  class InvoicesType
    STANDARD = "STANDARD".freeze
    AD_HOC = "AD_HOC".freeze
    CUSTOM = "CUSTOM".freeze
    COMPOSITE = "COMPOSITE".freeze
    STANDARD_ADVANCED = "STANDARD_ADVANCED".freeze
    ADHOC_ADVANCED = "ADHOC_ADVANCED".freeze

    def self.all_vars
      @all_vars ||= [STANDARD, AD_HOC, CUSTOM, COMPOSITE, STANDARD_ADVANCED, ADHOC_ADVANCED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if InvoicesType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #InvoicesType"
    end
  end
end
