=begin
#Togai Apis

#APIs for Togai App

The version of the OpenAPI document: 1.0
Contact: engg@togai.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module TogaiClient
  class MetricName
    EVENTS = "EVENTS".freeze
    USAGE = "USAGE".freeze
    METER_USAGE = "METER_USAGE".freeze
    NAMED_LICENSE_USAGE = "NAMED_LICENSE_USAGE".freeze
    REVENUE = "REVENUE".freeze
    USAGE_FOR_CYCLE = "USAGE_FOR_CYCLE".freeze
    REVENUE_FOR_CYCLE = "REVENUE_FOR_CYCLE".freeze

    def self.all_vars
      @all_vars ||= [EVENTS, USAGE, METER_USAGE, NAMED_LICENSE_USAGE, REVENUE, USAGE_FOR_CYCLE, REVENUE_FOR_CYCLE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if MetricName.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #MetricName"
    end
  end
end
