=begin
#Togai Apis

#APIs for Togai App

The version of the OpenAPI document: 1.0
Contact: engg@togai.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module TogaiClient
  class RateCardType
    MINIMUM_COMMITMENT = "MINIMUM_COMMITMENT".freeze
    BILLING_ENTITLEMENT = "BILLING_ENTITLEMENT".freeze
    CREDIT_GRANT = "CREDIT_GRANT".freeze
    ENTITLEMENT_OVERAGE = "ENTITLEMENT_OVERAGE".freeze
    FIXED_FEE = "FIXED_FEE".freeze
    LICENSE = "LICENSE".freeze
    USAGE = "USAGE".freeze

    def self.all_vars
      @all_vars ||= [MINIMUM_COMMITMENT, BILLING_ENTITLEMENT, CREDIT_GRANT, ENTITLEMENT_OVERAGE, FIXED_FEE, LICENSE, USAGE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if RateCardType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #RateCardType"
    end
  end
end
