=begin
#Togai Apis

#APIs for Togai App

The version of the OpenAPI document: 1.0
Contact: engg@togai.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module TogaiClient
  class SettingDataType
    STRING = "STRING".freeze
    NUMERIC = "NUMERIC".freeze
    JSON = "JSON".freeze
    JSON_LOGIC = "JSON_LOGIC".freeze

    def self.all_vars
      @all_vars ||= [STRING, NUMERIC, JSON, JSON_LOGIC].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if SettingDataType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #SettingDataType"
    end
  end
end
